### ISSUE TITLE
twl_dict_key_from_value weird behaviour

### ISSUE THREAD

**Issue by mgiraud** [juschaef/libtowel#11]
Sur ma branche, j'ai cree la fonction twl_dict_key_from_value qui fait ce qu'indique son nom.

Au niveau des test j'ai un segfault que je ne comprends pas :

```
twl_dict_add(lst, "key1", "data1");
twl_dict_add(lst, "key3", "data3");
twl_dict_add(lst, "key2", NULL);
twl_dict_add(lst, "key4", "data4");

mt_assert(strcmp(twl_dict_key_from_value(lst, cmp_value, "data3"), "key3") == 0);
mt_assert(strcmp(twl_dict_key_from_value(lst, cmp_value, NULL), "key2") == 0);
mt_assert(strcmp(twl_dict_key_from_value(lst, cmp_value, "data1"),"key1") == 0);
mt_assert(strcmp(twl_dict_key_from_value(lst, cmp_value, "data4"),"key4") == 0);
```

me fait un segfault au niveau de : 
    mt_assert(strcmp(twl_dict_key_from_value(lst, cmp_value, "data4"),"key4") == 0);

mais si je fais ca 
    twl_dict_add(lst, "key1", "data1");
    twl_dict_add(lst, "key3", "data3");
        twl_dict_add(lst, "key4", "data4");
    twl_dict_add(lst, "key2", NULL);

```
mt_assert(strcmp(twl_dict_key_from_value(lst, cmp_value, "data3"), "key3") == 0);
mt_assert(strcmp(twl_dict_key_from_value(lst, cmp_value, NULL), "key2") == 0);
mt_assert(strcmp(twl_dict_key_from_value(lst, cmp_value, "data1"),"key1") == 0);
mt_assert(strcmp(twl_dict_key_from_value(lst, cmp_value, "data4"),"key4") == 0);
```

J'ai pas de segfault.
@yyang42  ou @juschaef  pourrait checker svp ?

**Comment by yyang42** [comment]
Tu peux push le code et indiquer la branche ou ya twl_dict_key_from_value?

**Comment by mgiraud** [comment]
je check avec Antoine et on revient vers vous si on trouve pas. J'ai push sur le master de mon fork.
Edit c'est bon un probleme de double check pour les NULL, je PR la fonction

**Comment by yyang42** [comment]
Ok cool :) Dis moi si vous avez besoin d'aide.
